### ISSUE TITLE
SHA256 Mismatch during brew install 

### ISSUE THREAD

**Issue by manojkarthick** [yoannfleurydev/gitweb#113]
**Describe the bug**
When installing gitweb with Homebrew, there seems to a hash mismatch that prevents it from getting installed

**To Reproduce**
1. Install homebrew
2. Run `brew install gitweb`

**Expected behavior**
Installation should succeed 

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1 21A559 arm64

**Additional context**
Error message:
```
    Error: gitweb: SHA256 mismatch
    Expected: 484b1c56973e06c2ad7b33ccdaafa8ef6fba236681c7f8cd04027738b5335cd3
      Actual: 9a8887fe063fd619a40c15c099f47fddcb82b73720e3e87ccf76499e296d3591
```

**Comment by yoannfleurydev** [comment]
Hi. Thanks a lot for the bug report, I'm going to check that as soon as possible (probably this weekend).

**Comment by yoannfleurydev** [comment]
Just release the 0.3.4 version with its recipe for homebrew, this should be fixed. Thanks again for the feedback.

**Comment by manojkarthick** [comment]
Installation works now - Thanks for updating!
